services:
  backend:
    env_file:
      - .env.prod
    ports: "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db
  
  frontend:
    ports:
      - "80:80"
  
  db:
    env_file:
      .env.prod