version: '3.8'

services:
  backend:
    env_file:
      - .env.test
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
  
  db:
    env_file:
      .env.test
    ports:
      - "5432:5432"
    volumes:

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}