services:
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: production
    container_name: frontend_prod
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    command: [ "nginx", "-g", "daemon off;" ]
    restart: always
    env_file:
      - .env.prod
 
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: production
    container_name: backend_prod
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    ports: 
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    depends_on:
      - db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  db:
    container_name: db_prod
    image: postgres:15
    env_file:
      - .env.prod
    ports:
      - "5434:5432"
    volumes:
      - db_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}

volumes:
  db_prod: