services:
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development
    container_name: frontend_dev
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
  
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: development
    container_name: backend_dev
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    depends_on:
      - db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  db:
    container_name: db_dev
    image: postgres:15
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  db_dev: