services:
  backend:
    env_file:
      - .env.test
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
  
  db:
    container_name: db_test
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    volumes:
      - db_test:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  db_test: