services:
  backend:
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db
  
  frontend:
    volumes:
      - ./frontend:/app
  
  db:
    container_name: db_dev
    ports:
      - "5432:5432"
    volumes:
      - db_dev:/var/lib/postgresql/data
    env_file:
      - .env.dev
volumes:
  db_dev: