name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - test
      - prod
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Create .env file based on environment
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DEBUG: ${{ secrets.DEBUG }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            ENV_FILE=".env.dev"
          elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
            ENV_FILE=".env.test"
          elif [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            ENV_FILE=".env.prod"
          fi
          echo DATABASE_URL=${DATABASE_URL} >> $ENV_FILE
          echo DEBUG=${DEBUG} >> $ENV_FILE
          echo POSTGRES_USER=${POSTGRES_USER} >> $ENV_FILE
          echo POSTGRES_PASSWORD=${POSTGRES_PASSWORD} >> $ENV_FILE
          echo POSTGRES_DB=${POSTGRES_DB} >> $ENV_FILE

      - name: Make run-tests.sh executable
        run: chmod +x run-tests.sh

      - name: Run the test script
        run: ./run-tests.sh
